ALTER TABLE "Zone" ADD COLUMN "allowUserPost" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Zone" ADD COLUMN "allowUserReply" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Board" ADD COLUMN "allowUserPost" BOOLEAN;
ALTER TABLE "Board" ADD COLUMN "allowUserReply" BOOLEAN;
